[workspace]
members = [
  "crates/holochain_serialized_bytes",
  "test/holochain_serialized_bytes",
]
resolver = "2"

[workspace.lints.clippy]
style = "deny"
complexity = "deny"
perf = "deny"
correctness = "deny"
dbg_macro = "deny"
