name: test

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v23
      - name: Build Nix packages for dev shell
        run: nix develop -c $SHELL -c "rustc --version --verbose"
      - name: Run tests
        run: nix develop -c $SHELL -c "cargo test"
