name: test

on: [push]

jobs:
  cargo-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      # - uses: cachix/install-nix-action@v23
      #   with:
      #     nix_path: nixpkgs=channel:nixos-unstable
      - run: cargo test
